name: Nightly
on:
  schedule:
    - cron: '00 23 * * *'
jobs:
  nightly:
    uses: mullvad/rsw-public/.github/workflows/go-ci.yaml@master
    secrets:
      SLACK_FAILURE_WEBHOOK_URL: ${{ secrets.SLACK_RSW_BUILDS_URL }}
